version: "3"

services:


#######Servizi per Zabbix####################

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - bda_project
    ports:
      - '3306:3306'
    networks:
      bda_project:
        ipv4_address: 172.16.121.6
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - bda_project
    links:
      - mysql
    user: root
    restart: always
    ports:
      - '10051:10051'
    networks:
      bda_project:
        ipv4_address: 172.16.121.7
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
 #     - './zabbix/config:/etc/zabbix'
 #     - ./zabbix/data:/home/ZabbixExport:z
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - bda_project
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      bda_project:
        ipv4_address: 172.16.121.8
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=Europe/Rome
    depends_on:
      - mysql
#    volumes:
#      - './zabbix/config/zabbix.conf.php:/usr/share/zabbix/conf/zabbix.conf.php'
   

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      bda_project:
        ipv4_address: 172.16.121.10
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.16.121.7
    
networks:
  bda_project:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.121.0/24


